
<div data-bind="scope: 'custom-cart-section'" id="custom-cart-section">
   <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "custom-cart-section": {
                       "component": "AtPay_CustomPayment/js/custom-cart"
                   }
               }
           }
       }
   }
</script>